PACKAGE_NAME = "hello"
VERSION = "1.0.0"
TRAVELING_RUBY_VERSION = "20150210-2.1.5"

desc "Package your app"
#task :package => ['package:linux:x86', 'package:linux:x86_64', 'package:osx']
task :package => ['package:linux:x86_64', 'package:bundle_install']

namespace :package do
  namespace :linux do
    desc "Package your app for Linux x86"
    task :x86 => "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86.tar.gz" do
      create_package("linux-x86")
    end

    desc "Package your app for Linux x86_64"
    task :x86_64 => "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz" do
      create_package("linux-x86_64")
    end
  end

  desc "Package your app for OS X"
  task :osx => "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-osx.tar.gz" do
    create_package("osx")
  end

  desc "Install gems to local directory"
    task :bundle_install do
      sh "rm -rf packaging/tmp"
      sh "mkdir packaging/tmp"
      sh "cp Gemfile Gemfile.lock packaging/tmp/"
      Bundler.with_clean_env do
        sh "cd packaging/tmp && env BUNDLE_IGNORE_CONFIG=1 bundle install --path ../vendor --without development"
      end
      sh "rm -rf packaging/tmp"
      sh "rm -f packaging/vendor/*/*/cache/*"
    end
end

file "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86.tar.gz" do
  download_runtime("linux-x86")
end

file "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-linux-x86_64.tar.gz" do
  download_runtime("linux-x86_64")
end

file "packaging/traveling-ruby-#{TRAVELING_RUBY_VERSION}-osx.tar.gz" do
  download_runtime("osx")
end

def create_package(target)
  package_dir = "#{PACKAGE_NAME}-#{VERSION}-#{target}"
  sh "rm -rf #{package_dir}"
  sh "mkdir -p #{package_dir}/lib/app"
  sh "cp hello_world.rb #{package_dir}/lib/app/"
  sh "mkdir #{package_dir}/lib/ruby"
  sh "cp -a ~/.rvm/rubies/ruby-2.4.1/* #{package_dir}/lib/ruby"
  sh "cp packaging/wrapper.sh #{package_dir}/runit.sh"
  sh "cp packaging/wrapper.js #{package_dir}/lambda.js"
  if ENV['DO_COMPRESS']
    sh "cd #{package_dir}; zip -r ../lambda.zip *"
    sh "rm -rf #{package_dir}"
  end
end

def download_runtime(target)
  sh "cd packaging && curl -L -O --fail " +
    "https://d6r77u77i8pq3.cloudfront.net/releases/traveling-ruby-#{TRAVELING_RUBY_VERSION}-#{target}.tar.gz"
end
